/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SimulationScenarioIdRouteImport } from './routes/simulation.$scenarioId'
import { Route as AdminScenariosCreateRouteImport } from './routes/admin.scenarios.create'
import { Route as AdminScenariosScenarioIdEditRouteImport } from './routes/admin.scenarios.$scenarioId.edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationScenarioIdRoute = SimulationScenarioIdRouteImport.update({
  id: '/simulation/$scenarioId',
  path: '/simulation/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScenariosCreateRoute = AdminScenariosCreateRouteImport.update({
  id: '/admin/scenarios/create',
  path: '/admin/scenarios/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScenariosScenarioIdEditRoute =
  AdminScenariosScenarioIdEditRouteImport.update({
    id: '/admin/scenarios/$scenarioId/edit',
    path: '/admin/scenarios/$scenarioId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/simulation/$scenarioId': typeof SimulationScenarioIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/scenarios/create': typeof AdminScenariosCreateRoute
  '/admin/scenarios/$scenarioId/edit': typeof AdminScenariosScenarioIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/simulation/$scenarioId': typeof SimulationScenarioIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/scenarios/create': typeof AdminScenariosCreateRoute
  '/admin/scenarios/$scenarioId/edit': typeof AdminScenariosScenarioIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/simulation/$scenarioId': typeof SimulationScenarioIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/scenarios/create': typeof AdminScenariosCreateRoute
  '/admin/scenarios/$scenarioId/edit': typeof AdminScenariosScenarioIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/simulation/$scenarioId'
    | '/admin'
    | '/admin/scenarios/create'
    | '/admin/scenarios/$scenarioId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/simulation/$scenarioId'
    | '/admin'
    | '/admin/scenarios/create'
    | '/admin/scenarios/$scenarioId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/simulation/$scenarioId'
    | '/admin/'
    | '/admin/scenarios/create'
    | '/admin/scenarios/$scenarioId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SimulationScenarioIdRoute: typeof SimulationScenarioIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminScenariosCreateRoute: typeof AdminScenariosCreateRoute
  AdminScenariosScenarioIdEditRoute: typeof AdminScenariosScenarioIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/$scenarioId': {
      id: '/simulation/$scenarioId'
      path: '/simulation/$scenarioId'
      fullPath: '/simulation/$scenarioId'
      preLoaderRoute: typeof SimulationScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scenarios/create': {
      id: '/admin/scenarios/create'
      path: '/admin/scenarios/create'
      fullPath: '/admin/scenarios/create'
      preLoaderRoute: typeof AdminScenariosCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scenarios/$scenarioId/edit': {
      id: '/admin/scenarios/$scenarioId/edit'
      path: '/admin/scenarios/$scenarioId/edit'
      fullPath: '/admin/scenarios/$scenarioId/edit'
      preLoaderRoute: typeof AdminScenariosScenarioIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SimulationScenarioIdRoute: SimulationScenarioIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminScenariosCreateRoute: AdminScenariosCreateRoute,
  AdminScenariosScenarioIdEditRoute: AdminScenariosScenarioIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
